name: CI/CD

on:
  push:
    branches:
      - Node

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        run: |
          sshpass -p ${{ secrets.SSH_PRIVATE_KEY_DIGITAL }} ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.IP }} << EOF
            cd /app
            git pull origin Node
            npm install
            npm run build
            cd /dist
            pm2 stop all
            npm run production
          EOF